packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true
  sharp: false
  workerd: true

minimumReleaseAgeExclude:
  - "@tldraw/driver@5.2.2"
  - "@tldraw/editor@5.2.2"
  - "@tldraw/state-react@5.2.2"
  - "@tldraw/state@5.2.2"
  - "@tldraw/store@5.2.2"
  - "@tldraw/tlschema@5.2.2"
  - "@tldraw/utils@5.2.2"
  - "@tldraw/validate@5.2.2"
  - tldraw@5.2.2

onlyBuiltDependencies:
  - esbuild
  - workerd
